version: '3.8'

services:
  flink-jobmanager:
    build:
      context: .
      dockerfile: flink.Dockerfile
    hostname: flink-jobmanager
    container_name: flink-jobmanager
    ports:
      - "9081:9081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        rest.bind-port: 9081
        rest.port: 9081

  flink-taskmanager:
    build:
      context: .
      dockerfile: flink.Dockerfile
    hostname: flink-taskmanager
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    deploy:
      replicas: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 1

#  hue:
#    image: gethue/hue:latest
#    hostname: hue
#    container_name: hue
#    ports:
#      - "8888:8888"
#    depends_on:
#      - flink-jobmanager
#      - flink-taskmanager
#    deploy:
#      replicas: 1
#    environment:
#      FLINK_CONFIG: |
#        [notebook]
#        enable_notebook_2=true
#
#        [[interpreters]]
#
#        [[[flink]]]
#        name=Flink
#        interface=flink
#        options='{"url": "http://flink-jobmanager:9081"}'
#    command:
#      /bin/sh -c "mkdir -p /etc/hue/conf && echo \"FLINK_CONFIG\" > /etc/hue/conf/log.conf && ./startup.sh"

